name: Pack source

on:
    push:
        branches: [gh_actions_test, main]
    pull_request_target:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v3

            - name: Pack DungeonDodgePack
              shell: bash
              run: |
                echo "Zipping DungeonDodgePack"
                7z a DungeonDodgePack.zip ./DungeonDodgePack/
            
            - name: Transform path
              id: transform-path
              env:
                  tag_timestamp: '${{ github.event.head_commit.timestamp }}'
              run: |
                echo "new_timestamp=$ENV:tag_timestamp.replace(':',' ')" >> "$NEW_TIMESTAMP"

    post:
        needs: build
        runs-on: ubuntu-latest

        name: Deploy to Github Releases

        permissions: write-all

        strategy:
            fail-fast: false

        steps:
            - uses: actions/checkout@v3

            - name: Install Zip
              uses: montudor/action-zip@v1

            - name: Make a release
              uses: ncipollo/release-action@v1
              env:
                NEW_TIMESTAMP: ${{ steps.transform-path.outputs.NEW_TIMESTAMP }}
              with:
                artifacts: "../DungeonDodgePack.zip"
                tag: "$NEW_TIMESTAMP"
                name: "Pack update (${{ github.event.head_commit.timestamp }})"
                body: "Pack update (${{ github.ref }})"
                makeLatest: true
