name: Pack source

on:
    push:
        branches: [gh_actions_test, main]
    pull_request_target:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v3

            - name: Pack DungeonDodgePack
              shell: bash
              run: |
                echo "Zipping DungeonDodgePack"
                7z a DungeonDodgePack.zip ./DungeonDodgePack/
                
            - name: Make a release
              uses: ncipollo/release-action@v1
              with:
                artifacts: "../DungeonDodgePack.zip"
                tag: "${{ hashFiles(github.event.head_commit.modified) }}"
                name: "Pack update (${{ github.event.head_commit.timestamp }})"
                body: "Pack update (${{ github.ref }})"
                makeLatest: true

    deploy:
        needs: build
        name: Deploy to Github Releases
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        steps:
            - uses: actions/checkout@v3

            - name: Install Zip
              uses: montudor/action-zip@v1